#!/bin/bash
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

alias ll='ls -lht --reverse'
alias la='ls -A'
alias l='ls -CF'
alias file_size='du --summarize --human-readable'

## git 别名
# alias gd='git diff'
alias gstatus='git status'
alias gcommit='git add . && git commit -m'
alias gpush='git push origin master'
alias gdiff='git diff'

# 装逼，模仿《黑客军团》中将工具新建一个文件夹放入~/tools文件夹中
export PATH=~/tools:"$PATH"

# 使用bash -x参数时显示行号
export PS4='$LINENO + '

# Emacs
alias e='emacs24 -nw'
# 让emamcs图形界面支持中文输入
# 加入此条配置后会使用Emacs中进入info模式下时出现费字符。
# export LC_CTYPE=zh_CN.UTF-8

#支持Emacs命令行主题一致
# export TERM=xterm-256color
