#!/bin/bash
# 快速产看是否能联网
# Author: Claudio <3261958605@qq.com>
# Created: 2017-04-11 23:09:57
# Commentary:
# Code:

function ping_until_connected {
    if ! claudio_connected_to_internet_p; then
        spd-say "no, not connected"
        echo "重试..."
        sleep 5
        ping_until_connected
    else
        spd-say "yes, connected"
        echo $(claudio_color --color yellow "连接成功！")
    fi
}

ping_until_connected
exit
