#!/bin/bash
# FIXME: 没解决重复打印的问题
# 使用mplayer播放家目录中Music文件夹中的音乐文件

DIR=$HOME/Music					# 默认存放音频文件的文件夹
PLAYER=mplayer					# 默认播放器

# 辅助函数，确保文件夹中有音频文件
function contains_music {
	if [[ (-d $1) && $(find $1 -regextype "posix-egrep" -regex ".*\.(mp3|mp4|ogg)$" ) ]]; then
		echo true
	else
		echo false
	fi
}

# 确保~/Music文件夹存在且其中有音频文件
function ensure_dir {
	# 确保文件夹存在
	if [[ ! -d $DIR ]]; then
		echo "默认文件夹$DIR不存在" >&2
		exit 1
	fi

	# 确保文件夹中有音频文件.mp3或.ogg格式
	if [[ false ==  $(contains_music $DIR) ]]; then
		echo "$DIR中不存在可供播放的ogg或mp3文件" >&2
		exit 1
	fi
}

# 确保安装了mplayer播放器
function ensure_player {
	if [[ ! $(which $PLAYER) ]]; then
		echo -e "安装播放器：$PLAYER\n"
		sudo apt install $PLAYER
	fi
    return
}

# 显示菜单获取播放选择
play_list_dir=							# 存放音频文件夹的数组
dir_index=0				# 文件夹数组索引

# 获取含音乐文件的文件夹，并初始化play_list_dir和dir_index变量
function get_music_dirs {
	# 重置数组
    dir_index=0
	# for((i=0; i < "${play_list_dir[@]}"; i++)); do
	# 	play_list_dir[$i]="";
	# done

	#获取音乐文件夹
	for i in $DIR/*; do
		# 如果是存放有音频的文件夹
		if [[ true == $(contains_music $i) ]]; then
			play_list_dir[((dir_index++))]="$i"
			# echo $i 				# TEST
		fi
	done

	# 按字母顺序排序歌单
	play_list_dir=($(for i in "${play_list_dir[@]}"; do echo "$i"; done | sort --reverse))

}

function hint_select {
    echo "输入错误，正确选项为[0-$((dir_index - 1))]或'q'"
}

function menu {
	clear
	local items_per_line=5		# 每行打印多少项
	echo $(claudio_color --color light-blue "播放列表：")
	for (( i=0; i < dir_index; i++ )); do
		if (( (i % items_per_line) == 0)); then
			printf "\n"
		fi
		printf "%2s) %10s\t" $i $(claudio_color --color green "${play_list_dir[i]##*/}")
	done
	printf "\n\nq) 退出\n\n"

}

# 播放音乐文件
function play {
	ensure_dir
	ensure_player
	# 每次调研play函数时都重新读取文件夹
	# 使得播放过程中添加文件夹，跟换播放文件夹后可见
	get_music_dirs
	menu
	# 获取选择

	# echo "验证前\$REPLY = $REPLY \$dir_index=$dir_index" # TEST
	# 验证输入
	while true; do
		echo -n $(claudio_color --color blue "请选择：")
		read
		case $REPLY in
			[[:digit:]])
				if (($REPLY < 0 )) || (($REPLY >= $dir_index )); then
					hint_select
				else
					break
				fi
				;;
			q|Q) exit
				 ;;
			*) hint_select
			   ;;
		esac
	done

	local dir="${play_list_dir[REPLY]}"

	for music in $dir/*; do
		echo "正在播放：$music ..."
		echo -e "q)\t" $(claudio_color --color green "下一曲")
		echo -e "空格)\t" $(claudio_color --color green "暂停")
		$PLAYER "$music" 1>& /dev/null

	done

	play						# 重复播放

}

play
