#!/bin/bash
# 快速产看是否能联网
# Author: Claudio <3261958605@qq.com>
# Created: 2017-04-11 23:09:57
# Commentary:
# Code:

function ping_until_connected {
    if ! claudio_connected_to_internet_p; then
        spd-say "no, not connected"
        echo "重试..."
        sleep 5
        ping_until_connected
    else
        echo $(claudio_color --color green "连接成功本地服务器！")
        return 0
    fi
}

if ping_until_connected; then
    ping qq.com -c 1>& /dev/null
    echo $(claudio_color --color blue '成功连接广域网！')
    spd-say 'yes, connected to internet'
fi

exit
