#!/bin/bash
# 系统备份
# Author: Claudio <3261958605@qq.com>
# Created: 2017-04-11 19:33:03
# Commentary:
# Code:
mkdir --parents ~/Backup

echo $(claudio_color --color green "开始备份文件...")

rsync --archive --quiet --delete  --compress --compress-level=9 \
      ~/.ssh ~/.emacs.d ~/bin ~/python ~/Desktop ~/clang ~/Documents ~/Music \
      ~/Backup/backup \
    && \
    echo $(claudio_color --color green "备份成功\n")

exit
