#!/bin/bash

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
alias ll='ls -lht --reverse'
alias la='ls -A'
alias l='ls -CF'
alias du='du --summarize --human-readable'

# 文件夹切换
alias bk='cd ..'
alias bk1='cd ..'
alias bk2='cd ../..'
alias bk3='cd ../../..'

## git 别名
# alias gd='git diff'
alias gstatus='git status'
alias gcommit='git add . && git commit -m'
alias gpush='git push origin master'
alias gdiff='git diff'

# 装逼，模仿《黑客军团》中将工具新建一个文件夹放入~/tools文件夹中
export PATH=~/tools:~/python:~/bin:"$PATH"

# 使用bash -x参数时显示行号
export PS4='$LINENO + '

# Emacs
alias e='emacs24 -nw'
# export EDITOR='emacs24'

# 让emamcs图形界面支持中文输入
# 加入此条配置后会使用Emacs中进入info模式下时出现废字符。
# export LC_CTYPE=zh_CN.UTF-8

#支持Emacs命令行主题一致
# export TERM=xterm-256color

# python

# 添加后只能加载某个版本的路径，还没找到解决办法
# export PYTHONPATH=~/python:'/usr/lib/python35.zip':'/usr/lib/python3.5':'/usr/lib/python3.5/plat-x86_64-linux-gnu':'/usr/lib/python3.5/lib-dynload':'/usr/local/lib/python3.5/dist-packages':'/usr/lib/python3/dist-packages'

alias python='python3'
alias ipython='ipython3'

# 影响加载速度，暂时禁用
# the fuck
# eval "$(thefuck --alias)"

# 终端UI
# export LINES=1000
# export COLUMNS=1000

# powerline-status 除了美观以外，好像没有啥子卵用
# 影响启动速度
# if [[ -f `which powerline-daemon` ]];then
#     powerline-daemon -q
#     POWERLINE_BASH_CONTINUATION=1
#     POWERLINE_BASH_SELECT=1
#     # 为提高启动速度，手动获取添加到此次
#     # . `pip3 show powerline-status | grep Location | cut -f 2 -d ' '`/powerline/bindings/bash/powerline.sh
#     source /usr/local/lib/python3.5/dist-packages/powerline/bindings/bash/powerline.sh
# fi

# clang路径配置
export CPATH=~/clang/Strings:"$CPATH"
export C_INCLUDE_PATH=~/clang/Strings:"$C_INCLUDE_PATH"
