#!/bin/bash
function usage {
    echo "用法：${0##*/} [-m --message | -h --help]"
}

message="日常跟新"

# 处理参数，如果指定commit字符串
while [[ -n $1 ]]; do
	case $1 in
		-m|--message) shift
					  message="$1"
					  ;;
		-h|--help) usage
				   exit
				   ;;
		*) usage >&2
		   exit 1
	esac
	shift
done

if [[ -d ".git" ]]; then 		# 如果是git项目根目录
	# echo $(pwd)
	if [[ -z $(git diff) ]]; then # 如果无修改
		echo $(my_brown "无需跟新")
		exit
	else
		echo "需跟新"
		echo "添加所有更改："
		git add .
		echo "使用git commit '$message' Commit"
		git commit -m "$message"
		echo "向远程推送"
		git push origin master
		echo "远程跟新结束"
	fi
else
	echo $(my_yellow "不是git项目根目录") >&2
fi
